# Generated by Django 6.0.7 on 2026-08-03 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('window_size', models.IntegerField(default=288)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('param1', models.FloatField()),
                ('param2', models.FloatField()),
                ('param3', models.FloatField()),
                ('param4', models.FloatField()),
                ('param5', models.FloatField()),
                ('unit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='raw_data_timesta_1829f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('param1', models.FloatField()),
                ('param2', models.FloatField()),
                ('param3', models.FloatField()),
                ('param4', models.FloatField()),
                ('param5', models.FloatField()),
                ('unit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('param1_ma5m', models.FloatField(blank=True, null=True)),
                ('param1_ma15m', models.FloatField(blank=True, null=True)),
                ('param1_ma30m', models.FloatField(blank=True, null=True)),
                ('param1_change_rate', models.FloatField(blank=True, null=True)),
                ('param2_change_rate', models.FloatField(blank=True, null=True)),
                ('hour_of_day', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('param1_deviation_7d', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_data', to='data.processingjob')),
                ('raw_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='data.rawdata')),
            ],
            options={
                'db_table': 'processed_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='processed_d_timesta_2a9b93_idx')],
            },
        ),
    ]
